// <auto-generated />
using System;
using GardenTracker.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GardenTracker.Data.Migrations
{
    [DbContext(typeof(GardenTrackerDbContext))]
    [Migration("20260506012912_RenameRaisedBedsToBeds")]
    partial class RenameRaisedBedsToBeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GardenTracker.Core.Entities.Bed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DepthIn")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("ExpectedLifespanYears")
                        .HasColumnType("int");

                    b.Property<int>("GardenId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("InstalledDate")
                        .HasColumnType("date");

                    b.Property<decimal>("LengthFt")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Material")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WidthFt")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("GardenId");

                    b.ToTable("Beds");
                });

            modelBuilder.Entity("GardenTracker.Core.Entities.BedPlanting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BedId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantVarietyId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<int?>("SourceHarvestId")
                        .HasColumnType("int");

                    b.Property<int>("StartMethod")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("BedId");

                    b.HasIndex("PlantVarietyId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("SourceHarvestId");

                    b.HasIndex("SupplierId");

                    b.ToTable("BedPlantings");
                });

            modelBuilder.Entity("GardenTracker.Core.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("BedId")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("ExpenseDate")
                        .HasColumnType("date");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BedId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("GardenTracker.Core.Entities.Garden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Gardens");
                });

            modelBuilder.Entity("GardenTracker.Core.Entities.Harvest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BedId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("HarvestDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantVarietyId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BedId");

                    b.HasIndex("PlantVarietyId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Harvests");
                });

            modelBuilder.Entity("GardenTracker.Core.Entities.MarketPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlantTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("PlantVarietyId")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateOnly>("RecordedDate")
                        .HasColumnType("date");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlantTypeId");

                    b.HasIndex("PlantVarietyId");

                    b.HasIndex("SeasonId");

                    b.ToTable("MarketPrices");
                });

            modelBuilder.Entity("GardenTracker.Core.Entities.PlantType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PlantTypes");
                });

            modelBuilder.Entity("GardenTracker.Core.Entities.PlantVariety", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlantTypeId", "Name")
                        .IsUnique();

                    b.ToTable("PlantVarieties");
                });

            modelBuilder.Entity("GardenTracker.Core.Entities.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GardenId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GardenId", "Year")
                        .IsUnique();

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("GardenTracker.Core.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierType")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("GardenTracker.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GardenTracker.Core.Entities.WaterBill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsGardenActive")
                        .HasColumnType("bit");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("UsageCcf")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("UsageGallons")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("WaterBills");
                });

            modelBuilder.Entity("GardenTracker.Core.Entities.Bed", b =>
                {
                    b.HasOne("GardenTracker.Core.Entities.Garden", "Garden")
                        .WithMany("Beds")
                        .HasForeignKey("GardenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Garden");
                });

            modelBuilder.Entity("GardenTracker.Core.Entities.BedPlanting", b =>
                {
                    b.HasOne("GardenTracker.Core.Entities.Bed", "Bed")
                        .WithMany("Plantings")
                        .HasForeignKey("BedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GardenTracker.Core.Entities.PlantVariety", "PlantVariety")
                        .WithMany("Plantings")
                        .HasForeignKey("PlantVarietyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GardenTracker.Core.Entities.Season", "Season")
                        .WithMany("Plantings")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GardenTracker.Core.Entities.Harvest", "SourceHarvest")
                        .WithMany("SeedSavedPlantings")
                        .HasForeignKey("SourceHarvestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GardenTracker.Core.Entities.Supplier", "Supplier")
                        .WithMany("Plantings")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Bed");

                    b.Navigation("PlantVariety");

                    b.Navigation("Season");

                    b.Navigation("SourceHarvest");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("GardenTracker.Core.Entities.Expense", b =>
                {
                    b.HasOne("GardenTracker.Core.Entities.Bed", "Bed")
                        .WithMany("Expenses")
                        .HasForeignKey("BedId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GardenTracker.Core.Entities.Season", "Season")
                        .WithMany("Expenses")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GardenTracker.Core.Entities.Supplier", "Supplier")
                        .WithMany("Expenses")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Bed");

                    b.Navigation("Season");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("GardenTracker.Core.Entities.Garden", b =>
                {
                    b.HasOne("GardenTracker.Core.Entities.User", "User")
                        .WithMany("Gardens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GardenTracker.Core.Entities.Harvest", b =>
                {
                    b.HasOne("GardenTracker.Core.Entities.Bed", "Bed")
                        .WithMany("Harvests")
                        .HasForeignKey("BedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GardenTracker.Core.Entities.PlantVariety", "PlantVariety")
                        .WithMany("Harvests")
                        .HasForeignKey("PlantVarietyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GardenTracker.Core.Entities.Season", "Season")
                        .WithMany("Harvests")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bed");

                    b.Navigation("PlantVariety");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("GardenTracker.Core.Entities.MarketPrice", b =>
                {
                    b.HasOne("GardenTracker.Core.Entities.PlantType", "PlantType")
                        .WithMany("MarketPrices")
                        .HasForeignKey("PlantTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GardenTracker.Core.Entities.PlantVariety", "PlantVariety")
                        .WithMany("MarketPrices")
                        .HasForeignKey("PlantVarietyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GardenTracker.Core.Entities.Season", "Season")
                        .WithMany("MarketPrices")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlantType");

                    b.Navigation("PlantVariety");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("GardenTracker.Core.Entities.PlantVariety", b =>
                {
                    b.HasOne("GardenTracker.Core.Entities.PlantType", "PlantType")
                        .WithMany("Varieties")
                        .HasForeignKey("PlantTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlantType");
                });

            modelBuilder.Entity("GardenTracker.Core.Entities.Season", b =>
                {
                    b.HasOne("GardenTracker.Core.Entities.Garden", "Garden")
                        .WithMany("Seasons")
                        .HasForeignKey("GardenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Garden");
                });

            modelBuilder.Entity("GardenTracker.Core.Entities.WaterBill", b =>
                {
                    b.HasOne("GardenTracker.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GardenTracker.Core.Entities.Bed", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("Harvests");

                    b.Navigation("Plantings");
                });

            modelBuilder.Entity("GardenTracker.Core.Entities.Garden", b =>
                {
                    b.Navigation("Beds");

                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("GardenTracker.Core.Entities.Harvest", b =>
                {
                    b.Navigation("SeedSavedPlantings");
                });

            modelBuilder.Entity("GardenTracker.Core.Entities.PlantType", b =>
                {
                    b.Navigation("MarketPrices");

                    b.Navigation("Varieties");
                });

            modelBuilder.Entity("GardenTracker.Core.Entities.PlantVariety", b =>
                {
                    b.Navigation("Harvests");

                    b.Navigation("MarketPrices");

                    b.Navigation("Plantings");
                });

            modelBuilder.Entity("GardenTracker.Core.Entities.Season", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("Harvests");

                    b.Navigation("MarketPrices");

                    b.Navigation("Plantings");
                });

            modelBuilder.Entity("GardenTracker.Core.Entities.Supplier", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("Plantings");
                });

            modelBuilder.Entity("GardenTracker.Core.Entities.User", b =>
                {
                    b.Navigation("Gardens");
                });
#pragma warning restore 612, 618
        }
    }
}
